version: "2"

services:
  nginx:
    container_name: nginx
    image: cryptosis/nginx
    build:
      context: .
      dockerfile: operations/.docker/nginx/Dockerfile
    links:
      - node:api
    ports:
      - "80:80"
    networks:
      - cryptosis_network
  node:
    container_name: api
    image: cryptosis/api
    build:
      context: .
      dockerfile: operations/.docker/api/Dockerfile
    ports:
      - "8083:5000"
    env_file:
      - operations/env/api/.env
    networks:
      - cryptosis_network

networks:
  cryptosis_network:
    driver: bridge
