version: "2"

services:
  nginx:
    container_name: nginx
    image: investrackr/nginx
    build:
      context: .
      dockerfile: operations/.docker/nginx/Dockerfile
    links:
      - api:api
    ports:
      - "3000:80"
    networks:
      - investrackr_network
  node:
    container_name: suave
    working_dir: /app
    image: investrackr/suave
    build:
      context: .
      dockerfile: operations/.docker/suave/Dockerfile
    ports:
      - "8083:8083"
    networks:
      - investrackr_network

networks:
  hipster_network:
    driver: bridge
